version: '3.3'
services:

  server1:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: service-1
    ports:
      - 80:8000
      # - 32700:5432
        # command: /code/app/main.py
    extra_hosts:
      - "localhost:192.168.65.2"
    depends_on: 
      - "db"

  server2:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: service-2
    ports:
      - 81:8000
      # - 32700:5432
        # command: /code/app/main.py
    extra_hosts:
      - "localhost:192.168.65.2"
    depends_on: 
      - "db"

  nginx-proxy:
    image: nginx
    volumes:
      - ./nginx-a-a.conf:/etc/nginx/nginx.conf
    expose:
      - 9003
    ports:
      - "9003:9003"


  db:
    image:  postgres:11
    ports:
      - 32700:5432
    volumes:
      - ./data:/var/lib/postgresql/data

    environment:
      POSTGRES_USER:  root
      POSTGRES_PASSWORD:  root
      POSTGRES_DB: price_analysis

